server:
  port: 8083
spring:
  application:
    name: command-order
  datasource:
    url: jdbc:h2:mem:restaurant-order
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  snapshot:
    trigger:
      treshold:
        order: 100
  kafka:
#    client-id: order-command
    default-topic: axon-events
    producer:
      retries: 5
      bootstrap-servers: localhost:9092
      transaction-id-prefix: ordertx
    consumer:
      group-id: order-command-group
      bootstrap-servers: localhost:9092
  distributed:
    spring-cloud:
      fallback-to-http-get: false
    enabled: true
